### ISSUE TITLE
Cannot open the gitlab repository of 'ros enabled orbslam2'

### ISSUE THREAD

**Issue by aahegde** [TUMFTM/orbslam-map-saving-extension#1]
Hi, I tried to click on the ros-enabled version of ORB-SLAM2. This, hovewer asks me for the login details as shown below:
![Screenshot from 2020-07-10 10-27-45](https://user-images.githubusercontent.com/37207823/87133790-20d6ff80-c298-11ea-9923-cd0f001b5d89.png)

Unfortunately, not many of us have access here. Can you maybe make this repository (ros-enabled version) open?

**Comment by jingyibo123** [comment]
there's an extra " in the end of the link....

https://gitlab.tu-berlin.de/breakdowncookie/ORB_SLAM2

**Comment by jingyibo123** [comment]
@fnobis 
It would be great to provide from which commit of the [ORB-SLAM2 repo](https://gitlab.tu-berlin.de/breakdowncookie/ORB_SLAM2) you started this work, or even better, rebase the commit history so we could know which parts of code are related....

**Comment by fnobis** [comment]
Thank you for pointing that out. We build upon commit [68f40a95](https://gitlab.tu-berlin.de/breakdowncookie/ORB_SLAM2/commit/68f40a95d92d2239ac49fe79dc40c70c43ed32ca)
